### ISSUE TITLE
Use new apple JSON endpoints

### ISSUE THREAD

**Issue by tmc** [progrium/macschema#22]
The Apple Developer Documentation is now apparently rendered from backing JSON documents. We should change MacSchema to use these as source information which will simplify things.

**Comment by programmingkidx** [comment]
Can we access these JSON documents?

**Comment by tmc** [comment]
Yes, for example: https://developer.apple.com/tutorials/data/documentation/appkit/nswindow.json?language=objc

**Comment by programmingkidx** [comment]
Excellent discovery 👏
