### ISSUE TITLE
Frameworks missing from new Apple Developer Docs DOM

### ISSUE THREAD

**Issue by tmc** [progrium/macschema#23]
The new Mac developer docs don't include frameworks as they're used to, which means we're not populating them anymore. I think we need another mechanism for including this, perhaps a cli flag?

**Comment by programmingkidx** [comment]
We could make a database of foundation and appkit framework classes. Here is a list of Foundation framework classes: https://developer.apple.com/documentation/swift/working-with-foundation-types

**Comment by progrium** [comment]
Isn't the framework in the URL?

**Comment by progrium** [comment]
Can you be more specific about what changed?

**Comment by tmc** [comment]
> Can you be more specific about what changed?

https://github.com/progrium/macschema/blob/bdb0e004ad3c4fa478103360d49475b9a86f511f/schema/fetch.go#L40 this line never populates `t.Frameworks`

**Comment by progrium** [comment]
Oh for topics. Do you happen to know what was in there? It seems there are a couple cases where something can live in multiple frameworks (Appkit, UIKit) depending on platform, but if talking about a specific API it will live in one framework. Do you think this is still important? I'm not sure I used it, it just seemed like it would be good to grab.
